# Generated by Django 3.1.1 on 2020-11-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_final', '0002_auto_20201108_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn13',
            field=models.CharField(max_length=13),
        ),
    ]
