# Generated by Django 3.1.1 on 2020-11-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_final', '0003_auto_20201108_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='discount',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
