# Generated by Django 3.1.1 on 2020-10-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('1', 'Мужчина'), ('0', 'Женщина')], max_length=1, null=True),
        ),
    ]
