# Generated by Django 3.1.1 on 2020-10-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_user_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
