# Generated by Django 3.1.1 on 2020-10-13 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_cart'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'product')},
        ),
    ]
