# Generated by Django 3.1.1 on 2020-10-13 18:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
