# Generated by Django 3.1.1 on 2020-10-28 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0006_cart'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'product')},
        ),
    ]
